-- MySQL Script generated by MySQL Workbench
-- Thu Apr  2 12:54:37 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema FlightReservation
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema FlightReservation
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FlightReservation` DEFAULT CHARACTER SET utf8 ;
USE `FlightReservation` ;

-- -----------------------------------------------------
-- Table `FlightReservation`.`Login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FlightReservation`.`Login` (
  `idAccount` INT NOT NULL,
  `username` VARCHAR(15) NULL DEFAULT NULL,
  `userPassword` VARCHAR(25) NULL DEFAULT NULL,
  PRIMARY KEY (`idAccount`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FlightReservation`.`Passenger`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FlightReservation`.`Passenger` (
  `idPassenger` INT NOT NULL,
  `firstName` VARCHAR(25) NULL DEFAULT NULL,
  `lastName` VARCHAR(25) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `Login_idAccount` INT NOT NULL,
  PRIMARY KEY (`idPassenger`, `Login_idAccount`),
  INDEX `fk_Passenger_Login1_idx` (`Login_idAccount` ASC) VISIBLE,
  CONSTRAINT `fk_Passenger_Login1`
    FOREIGN KEY (`Login_idAccount`)
    REFERENCES `FlightReservation`.`Login` (`idAccount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FlightReservation`.`Airport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FlightReservation`.`Airport` (
  `idAirport` INT NOT NULL,
  `city` VARCHAR(25) NULL DEFAULT NULL,
  `country` VARCHAR(25) NULL DEFAULT NULL,
  `countryCode` VARCHAR(3) NULL DEFAULT NULL,
  PRIMARY KEY (`idAirport`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FlightReservation`.`Flight`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FlightReservation`.`Flight` (
  `idFlight` INT NOT NULL,
  `departureTime` VARCHAR(15) NULL DEFAULT NULL,
  `arrivalTime` VARCHAR(15) NULL DEFAULT NULL,
  `Flightcol` VARCHAR(45) NULL DEFAULT NULL,
  `Arrival_Airport_id` INT NOT NULL,
  `Departure_Airport_id` INT NOT NULL,
  PRIMARY KEY (`idFlight`, `Arrival_Airport_id`, `Departure_Airport_id`),
  INDEX `fk_Flight_Airport1_idx` (`Arrival_Airport_id` ASC) VISIBLE,
  INDEX `fk_Flight_Airport2_idx` (`Departure_Airport_id` ASC) VISIBLE,
  CONSTRAINT `fk_Flight_Airport1`
    FOREIGN KEY (`Arrival_Airport_id`)
    REFERENCES `FlightReservation`.`Airport` (`idAirport`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Flight_Airport2`
    FOREIGN KEY (`Departure_Airport_id`)
    REFERENCES `FlightReservation`.`Airport` (`idAirport`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FlightReservation`.`Reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FlightReservation`.`Reservation` (
  `idReservation` INT NOT NULL,
  `rentalCar` VARCHAR(3) NULL DEFAULT 'No',
  `shuttle` VARCHAR(3) NULL DEFAULT 'No',
  `hotel` VARCHAR(3) NULL DEFAULT 'No',
  `seatPref` VARCHAR(15) NULL DEFAULT 'No Preference',
  `Flight_idFlight` INT NOT NULL,
  `Passenger_idPassenger` INT NOT NULL,
  PRIMARY KEY (`idReservation`, `Flight_idFlight`, `Passenger_idPassenger`),
  INDEX `fk_Reservation_Flight1_idx` (`Flight_idFlight` ASC) VISIBLE,
  INDEX `fk_Reservation_Passenger1_idx` (`Passenger_idPassenger` ASC) VISIBLE,
  CONSTRAINT `fk_Reservation_Flight1`
    FOREIGN KEY (`Flight_idFlight`)
    REFERENCES `FlightReservation`.`Flight` (`idFlight`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservation_Passenger1`
    FOREIGN KEY (`Passenger_idPassenger`)
    REFERENCES `FlightReservation`.`Passenger` (`idPassenger`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
